apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: transformer
  annotations:
    run.googleapis.com/ingress: internal
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '20'
    spec:
      serviceAccountName: cloud-run-engine@PROJECT_ID_PLACEHOLDER.iam.gserviceaccount.com
      containerConcurrency: 10
      timeoutSeconds: 900
      containers:
      - image: IMAGE_URL_PLACEHOLDER
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: ENV
          value: prod
        - name: SERVICE_NAME
          value: transformer
        - name: SERVICE_VERSION
          value: '0.1.0'
        - name: GCP_PROJECT_ID
          value: PROJECT_ID_PLACEHOLDER
        - name: GCP_REGION
          value: europe-west1
        - name: GCS_BUCKET_NAME
          value: BUCKET_NAME_PLACEHOLDER
        - name: MAX_FILE_SIZE_MB
          value: '100'
        - name: MAX_ARCHIVE_SIZE_MB
          value: '500'
        - name: SPEECH_LANGUAGE_EN
          value: en-US
        - name: SPEECH_LANGUAGE_CS
          value: cs-CZ
        - name: LOG_LEVEL
          value: INFO
        resources:
          limits:
            cpu: '2'
            memory: 2Gi
